version: '3.8'

services:
  telegram-bot:
    build: .
    volumes:
      - ./chroma_data:/app/persist
      - ./onnx_models:/root/.cache/chroma/onnx_models
      - ./.env:/app/.env
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - WOLFRAMALPHA_APP_ID=${WOLFRAMALPHA_APP_ID}