version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    volumes:
      - ./chroma_data:/app/persist
      - ./onnx_models:/home/appuser/.cache/chroma/onnx_models
      - ./.env:/app/.env
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - WOLFRAMALPHA_APP_ID=${WOLFRAMALPHA_APP_ID}